services:
  api:
    container_name: api
    depends_on:
      - postgres
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./api:/api
    build: ./api
  postgres:
    container_name: postgres
    image: postgres:17
    env_file:
      - ./api/.env
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgres/data
volumes:
  pgdata:


